#!/usr/bin/env bash

readonly GREEN='\033[0;32m'
readonly RED='\033[0;31m'
readonly NC='\033[0m'

bridges=("br-admin" "br-webserver" "br-user")

missing_bridges=()
existing_bridges=()

for bridge in "${bridges[@]}"; do
    if ip link show "$bridge" &>/dev/null; then
        existing_bridges+=("$bridge")
    else
        missing_bridges+=("$bridge")
    fi
done

if [[ ${#missing_bridges[@]} -gt 0 ]]; then
   # Create bridges
    for bridge in "${missing_bridges[@]}"; do
        sudo ip link add name "$bridge" type bridge
        sudo ip link set "$bridge" up
    done
    echo -e "Created bridges: ${GREEN}${missing_bridges[*]}${NC}"
fi

# Checking if there's any resources in use
if [[ -n $(terraform state list) ]]; then
  terraform destroy -auto-approve
fi

terraform apply -auto-approve

terraform output -json hosts_for_ansible \
  | jq -r 'to_entries[] | "[" + .key + "]\n" + (.value | join("\n")) + "\n"' > ../ansible/inventory.ini
